-- 1번 코드
SELECT DATE_FORMAT(ONLINE_SALE.SALES_DATE, "%Y") AS 'YEAR',
    DATE_FORMAT(ONLINE_SALE.SALES_DATE, "%c") AS 'MONTH',
    GENDER,
    COUNT(DISTINCT ONLINE_SALE.USER_ID) AS 'USER'
FROM USER_INFO
JOIN ONLINE_SALE
    ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY DATE_FORMAT(ONLINE_SALE.SALES_DATE, "%Y"), DATE_FORMAT(ONLINE_SALE.SALES_DATE, "%c"), GENDER
ORDER BY DATE_FORMAT(ONLINE_SALE.SALES_DATE, "%Y"), DATE_FORMAT(ONLINE_SALE.SALES_DATE, "%c"), GENDER;


-- 2번 코드
SELECT YEAR(S.SALES_DATE) AS YEAR,
    MONTH(S.SALES_DATE) AS MONTH,
    I.GENDER,
    COUNT(DISTINCT I.USER_ID) AS USERS
FROM USER_INFO I
INNER JOIN ONLINE_SALE S
    ON I.USER_ID = S.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3;

-- 1번 코드가 틀린 이유
-- DATE_FORMAT은 연도와 월을 문자열 형식으로 변환
-- YEAR와 MONTH는 연도와 월을 숫자 형태로 변환
-- 차이점은 이 부분이기에 1번코드는 DATE_FORMAT 사용으로 인해 틀린듯.